version: '2.4'
services:
  main:
    build: 'main'
    container_name: main
    ports:
      - '80:80'
      - '25520:25520'
    mem_limit: 2048m
    mem_reservation: 1024m
    expose:
      - 80
      - 25520
    environment:
      - port=25520
      - webbind=main
      - bind=main
      - verbose=-v
    networks:
      - network
  cache:
    build: 'cache'
    container_name: cache
    ports:
      - '25521:25521'
    expose:
      - 25521
    environment:
      - port=25521
      - bind=cache
      - target=http://main
      - verbose=-v
    networks:
      - network
    mem_limit: 2048m
    mem_reservation: 1024m
  videoprocessor:
    build: 'video-processor-jcodec'
    container_name: videoprocessor
    ports:
      - '25522:25522'
    expose:
      - 25522
    environment:
      - port=25522
      - bind=videoprocessor
      - target=http://main
      - verbose=-v
    networks:
      - network
    mem_limit: 2048m
    mem_reservation: 1024m
networks:
  network: