FROM openjdk:12

ENV webport 80
ENV webbind 127.0.0.1
ENV port 25520
ENV bind 127.0.0.1
ENV name itsnotasciilive
ENV target http://localhost

COPY target/main-1.0-allinone.jar /main-1.0.jar
CMD /usr/bin/java -cp /main-1.0.jar live.itsnotascii.Main --webport ${webport} --webbind ${webbind} --port ${port} --bind ${bind} --name ${name} --target ${target}